function [data,perc_rect] = dlc_preprocess2(rawdata)
%DLC_PREPROCESS     filter data based on data-driven threshold
%   [DATA_RECT, PERC_RECT] = DLC_PREPROCESS(DATA,LLH) outputs the rectified data and percent rectified for each label.
%
%   INPUTS:
%   RAWDATA    A matrix generated by DeepLabCut (rows of observations & columns of x, y, and likelihoods).
%   LLH    Likelihood threshold cut-off. User should base this on how the labeled videos from DeepLabCut looks. Default is 0.1.
%
%   OUTPUTS:
%   DATA    Data matrix rectified after low-pass filter replacing the value with the most recent confident x,y.
%   PERC_RECT    Percent rectified for each body part.  This is just to inform the user how much data is below the threshold. 
%   Consider retraining/refining the network if this value is above 15%.
%
%   Examples:
%   clear rawdata;
%   load MsInOpenFieldRAW.mat
%   [data,perc_rect] = dlc_preprocess(rawdata,0.1);
%
%   Created by Alexander Hsu, Date: 122019
%   Contact ahsu2@andrew.cmu.edu

    if isstruct(rawdata) || iscell(rawdata)
        error('Input data has to be a matrix');
    end
    fprintf('Filtering low likelihood data points and replacing with the most recent position... \n');
    % Get rid of hind paws to speed up all following analyses
    datax = rawdata(:,[2:3:17]);
    datay = rawdata(:,[3:3:18]);
    data_lh = rawdata(:,[4:3:19]);
    % filter out likelihood below llh
    for x = 1:length(data_lh(1,:))
        if x <= 3
            [a b] = hist(data_lh(:,x));
            rise_a = find(diff(a)>=0);
            if rise_a(1) > 1
                llh = b(rise_a(1)-1);
            else
                llh = b(rise_a(2)-1);
            end
        else
            llh = 0.2;
        end
        perc_rect(x) = length(find(data_lh(:,x) < llh))/length(data_lh);
        data(1,(2*x-1):2*x) = [datax(1,x),datay(1,x)];
        for i = 2:length(data_lh)
            if  data_lh(i,x) < llh
                data(i,(2*x-1):2*x) = data(i-1,(2*x-1):2*x);
            else
                data(i,(2*x-1):2*x) = [datax(i,x),datay(i,x)];
            end
        end
    end
return
